### ISSUE TITLE
delete this repository

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-Core#64]
This repository is superseded by the new https://github.com/pldn/LDWizard. If I am not mistaken we should be able to just remove this repo completely? Or is there still a dependency with https://github.com/netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard?

**Comment by ddeboer** [comment]
I added a reference to https://github.com/pldn/LDWizard and archived the repo.
